### ISSUE TITLE
Example in Table 4.1 is not conform with our schema

### ISSUE THREAD

**Issue by RKrahl** [rdawg-pidinst/White-paper#3]
The example of Handle record of an instrument identifier in Table 4.1 does not fully conform with the PIDINST schema:

- The value of `identiferType` is "MeasuringInstrument".  That would be the type of the resource that the metadata record describes. The type of the identifier should be "Handle" in this case. (Note that the schema only lists "PIDINST" as permitted value, but that was meant to be a place holder for the identifier type being used. It was put there before we considered the actual implementations with DataCite and ePIC.)
- `modelName` is set as a sub property of `Manufacturer`. This should be a in separate property `Model` according to the schema. (Note that this has been changed with rdawg-pidinst/schema#40 in the schema.)

I admit that this is mainly due to ambiguities in the schema and to changes that have been made in the schema after you registered the PID. Nevertheless, if we provide an example to illustrate the schema, we should try our best to conform to it.

**Comment by louatbodc** [comment]
I think we had decided in one meeting to use MeasuringInstrument but we should ensure the same is being used between DataCIte and ePIC implementations.

ModelName does not exist in the ePIC implementation and I think this is the thing Ulrich wanted to correct. I'll contact him.

**Comment by louatbodc** [comment]
Updates in:
https://github.com/rdawg-pidinst/white-paper/pull/11
